apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  #  googleCloudBuild:
  #    projectId: rupnet-ticketing
  artifacts:
    - image: savan25/rupnet-ticketing/rupnet_event_booking_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: savan25/rupnet-ticketing/client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.tsx"
            dest: .
          - src: "**/*.js"
            dest: .
          - src: "**/*.jsx"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.scss"
            dest: .

# Port forwarding configuration
portForward:
  - resourceType: deployment
    resourceName: auth-mongo-depl
    port: 27017
    localPort: 27017