apiVersion: skaffold/v2beta1
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
#  local:
#    push: false
  googleCloudBuild:
    projectId: rupnet-ticketing
  artifacts:
    - image: us.gcr.io/rupnet-ticketing/rupnet_event_booking_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
